"""empty message

Revision ID: 5c651858b23e
Revises: f3b4b31e7116
Create Date: 2017-11-16 16:34:05.075780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c651858b23e'
down_revision = 'f3b4b31e7116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_no', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('company_id'),
    sa.UniqueConstraint('company_name'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_no')
    )
    op.drop_table('Company')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Company',
    sa.Column('company_id', sa.INTEGER(), server_default=sa.text(u'nextval(\'"Company_company_id_seq"\'::regclass)'), nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('phone_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('company_id', name=u'Company_pkey'),
    sa.UniqueConstraint('company_name', name=u'Company_company_name_key'),
    sa.UniqueConstraint('email', name=u'Company_email_key'),
    sa.UniqueConstraint('phone_no', name=u'Company_phone_no_key')
    )
    op.drop_table('company')
    # ### end Alembic commands ###
