"""empty message

Revision ID: 7e38500f60e7
Revises: 70dde7a8da77
Create Date: 2017-11-19 10:33:46.413545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e38500f60e7'
down_revision = '70dde7a8da77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'address',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('company', 'company_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('company', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('company', 'phone_no',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(u'company_company_name_key', 'company', type_='unique')
    op.drop_constraint(u'company_email_key', 'company', type_='unique')
    op.drop_constraint(u'company_phone_no_key', 'company', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'company_phone_no_key', 'company', ['phone_no'])
    op.create_unique_constraint(u'company_email_key', 'company', ['email'])
    op.create_unique_constraint(u'company_company_name_key', 'company', ['company_name'])
    op.alter_column('company', 'phone_no',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('company', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('company', 'company_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('company', 'address',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
